// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGTUGORexMTDl-o-cIzj8VfVSCrjcV3uE',
    appId: '1:192808880989:web:93c84c85e0b0cb63b436b4',
    messagingSenderId: '192808880989',
    projectId: 'wechat-6ec83',
    authDomain: 'wechat-6ec83.firebaseapp.com',
    storageBucket: 'wechat-6ec83.appspot.com',
    measurementId: 'G-D7JHFQ0V8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPLoS2__qYOEyDK7Owwxw8sFmDkeQ8qZM',
    appId: '1:192808880989:android:c301fc67b20ec57fb436b4',
    messagingSenderId: '192808880989',
    projectId: 'wechat-6ec83',
    storageBucket: 'wechat-6ec83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3QRowinwvhYrrEyAfirbwwFc6tRzfVic',
    appId: '1:192808880989:ios:81ad14dfe529de7bb436b4',
    messagingSenderId: '192808880989',
    projectId: 'wechat-6ec83',
    storageBucket: 'wechat-6ec83.appspot.com',
    androidClientId: '192808880989-3aq366ajk7095s47nstf796ootcthvhh.apps.googleusercontent.com',
    iosClientId: '192808880989-1669qqep33jf77837q9372cq5be9dmtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3QRowinwvhYrrEyAfirbwwFc6tRzfVic',
    appId: '1:192808880989:ios:81ad14dfe529de7bb436b4',
    messagingSenderId: '192808880989',
    projectId: 'wechat-6ec83',
    storageBucket: 'wechat-6ec83.appspot.com',
    androidClientId: '192808880989-3aq366ajk7095s47nstf796ootcthvhh.apps.googleusercontent.com',
    iosClientId: '192808880989-1669qqep33jf77837q9372cq5be9dmtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );
}
